name: Build bumperbot workspace

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up ROS 2
        # https://docs.ros.org/en/jazzy/Installation/Alternatives/Ubuntu-Install-Binary.html
        run: |
          sudo apt update && sudo apt install locales
          sudo locale-gen en_US en_US.UTF-8
          sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
          export LANG=en_US.UTF-8
          sudo apt install software-properties-common
          sudo add-apt-repository universe
          sudo apt update && sudo apt install -y curl gnupg lsb-release tar bzip2 wget
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install -y ros-dev-tools
          sudo apt install -y ros-jazzy-desktop
          sudo apt install -y python3-colcon-common-extensions

      - name: Install dependencies
        run: 
          sudo apt install -y python3-pip
          pip3 install -r requirements.txt
          sudo apt install -y python3-rosdep
          sudo rosdep init
          rosdep update
          rosdep install --from-paths src --ignore-src --rosdistro jazzy -y

      - name: Build the ROS 2 workspace
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --symlink-install

      - name: Run tests
        run: |
          source /opt/ros/jazzy/setup.bash
          source install/setup.bash
          colcon test

      - name: Upload build results
        uses: actions/upload-artifact@v3
        with:
          name: ros2-build-results
          path: install
